export default [
  "survey",
  "java_script_flavors_clojure_script",
  "java_script_flavors_what_do_you_like_👍_about_clojure_script",
  "java_script_flavors_what_do_you_dislike_👎_about_clojure_script",
  "java_script_flavors_elm",
  "java_script_flavors_what_do_you_like_👍_about_elm",
  "java_script_flavors_what_do_you_dislike_👎_about_elm",
  "java_script_flavors_es_6",
  "java_script_flavors_what_do_you_like_👍_about_es_6",
  "java_script_flavors_what_do_you_dislike_👎_about_es_6",
  "java_script_flavors_flow",
  "java_script_flavors_what_do_you_like_👍_about_flow",
  "java_script_flavors_what_do_you_dislike_👎_about_flow",
  "java_script_flavors_reason",
  "java_script_flavors_what_do_you_like_👍_about_reason",
  "java_script_flavors_what_do_you_dislike_👎_about_reason",
  "java_script_flavors_type_script",
  "java_script_flavors_what_do_you_like_👍_about_type_script",
  "java_script_flavors_what_do_you_dislike_👎_about_type_script",
  "java_script_flavors_other_java_script_flavors_options",
  "java_script_flavors_on_a_scale_of_one_to_five_how_happy_are_you_with_available_java_script_flavors_options",
  "front_end_angular",
  "front_end_what_do_you_like_👍_about_angular",
  "front_end_what_do_you_dislike_👎_about_angular",
  "front_end_ember",
  "front_end_what_do_you_like_👍_about_ember",
  "front_end_what_do_you_dislike_👎_about_ember",
  "front_end_polymer",
  "front_end_what_do_you_like_👍_about_polymer",
  "front_end_what_do_you_dislike_👎_about_polymer",
  "front_end_preact",
  "front_end_what_do_you_like_👍_about_preact",
  "front_end_what_do_you_dislike_👎_about_preact",
  "front_end_react",
  "front_end_what_do_you_like_👍_about_react",
  "front_end_what_do_you_dislike_👎_about_react",
  "front_end_vue_js",
  "front_end_what_do_you_like_👍_about_vue_js",
  "front_end_what_do_you_dislike_👎_about_vue_js",
  "front_end_other_front_end_options",
  "front_end_on_a_scale_of_one_to_five_how_happy_are_you_with_available_front_end_options",
  "data_layer_apollo",
  "data_layer_what_do_you_like_👍_about_apollo",
  "data_layer_what_do_you_dislike_👎_about_apollo",
  "data_layer_graph_ql",
  "data_layer_what_do_you_like_👍_about_graph_ql",
  "data_layer_what_do_you_dislike_👎_about_graph_ql",
  "data_layer_mobx",
  "data_layer_what_do_you_like_👍_about_mobx",
  "data_layer_what_do_you_dislike_👎_about_mobx",
  "data_layer_redux",
  "data_layer_what_do_you_like_👍_about_redux",
  "data_layer_what_do_you_dislike_👎_about_redux",
  "data_layer_relay",
  "data_layer_what_do_you_like_👍_about_relay",
  "data_layer_what_do_you_dislike_👎_about_relay",
  "data_layer_other_data_layer_options",
  "data_layer_on_a_scale_of_one_to_five_how_happy_are_you_with_available_data_layer_options",
  "back_end_express",
  "back_end_what_do_you_like_👍_about_express",
  "back_end_what_do_you_dislike_👎_about_express",
  "back_end_feathers",
  "back_end_what_do_you_like_👍_about_feathers",
  "back_end_what_do_you_dislike_👎_about_feathers",
  "back_end_koa",
  "back_end_what_do_you_like_👍_about_koa",
  "back_end_what_do_you_dislike_👎_about_koa",
  "back_end_meteor",
  "back_end_what_do_you_like_👍_about_meteor",
  "back_end_what_do_you_dislike_👎_about_meteor",
  "back_end_next_js",
  "back_end_what_do_you_like_👍_about_next_js",
  "back_end_what_do_you_dislike_👎_about_next_js",
  "back_end_sails",
  "back_end_what_do_you_like_👍_about_sails",
  "back_end_what_do_you_dislike_👎_about_sails",
  "back_end_other_back_end_options",
  "back_end_on_a_scale_of_one_to_five_how_happy_are_you_with_available_back_end_options",
  "testing_ava",
  "testing_what_do_you_like_👍_about_ava",
  "testing_what_do_you_dislike_👎_about_ava",
  "testing_enzyme",
  "testing_what_do_you_like_👍_about_enzyme",
  "testing_what_do_you_dislike_👎_about_enzyme",
  "testing_jasmine",
  "testing_what_do_you_like_👍_about_jasmine",
  "testing_what_do_you_dislike_👎_about_jasmine",
  "testing_jest",
  "testing_what_do_you_like_👍_about_jest",
  "testing_what_do_you_dislike_👎_about_jest",
  "testing_karma",
  "testing_what_do_you_like_👍_about_karma",
  "testing_what_do_you_dislike_👎_about_karma",
  "testing_mocha",
  "testing_what_do_you_like_👍_about_mocha",
  "testing_what_do_you_dislike_👎_about_mocha",
  "testing_storybook",
  "testing_what_do_you_like_👍_about_storybook",
  "testing_what_do_you_dislike_👎_about_storybook",
  "testing_other_testing_options",
  "testing_on_a_scale_of_one_to_five_how_happy_are_you_with_available_testing_options",
  "mobile_desktop_electron",
  "mobile_desktop_what_do_you_like_👍_about_electron",
  "mobile_desktop_what_do_you_dislike_👎_about_electron",
  "mobile_desktop_ionic",
  "mobile_desktop_what_do_you_like_👍_about_ionic",
  "mobile_desktop_what_do_you_dislike_👎_about_ionic",
  "mobile_desktop_native_apps",
  "mobile_desktop_what_do_you_like_👍_about_native_apps",
  "mobile_desktop_what_do_you_dislike_👎_about_native_apps",
  "mobile_desktop_native_script",
  "mobile_desktop_what_do_you_like_👍_about_native_script",
  "mobile_desktop_what_do_you_dislike_👎_about_native_script",
  "mobile_desktop_phone_gap_cordova",
  "mobile_desktop_what_do_you_like_👍_about_phone_gap_cordova",
  "mobile_desktop_what_do_you_dislike_👎_about_phone_gap_cordova",
  "mobile_desktop_react_native",
  "mobile_desktop_what_do_you_like_👍_about_react_native",
  "mobile_desktop_what_do_you_dislike_👎_about_react_native",
  "mobile_desktop_other_mobile_desktop_options",
  "mobile_desktop_on_a_scale_of_one_to_five_how_happy_are_you_with_available_mobile_desktop_options",
  "other_tools_other_languages",
  "other_tools_utility_libraries",
  "other_tools_text_editors",
  "other_tools_browser_ap_is",
  "other_tools_build_tools",
  "opinion_questions_java_script_is_moving_in_the_right_direction",
  "opinion_questions_building_java_script_apps_is_overly_complex_right_now",
  "opinion_questions_java_script_is_over_used_online",
  "opinion_questions_i_enjoy_building_java_script_apps",
  "opinion_questions_i_would_like_java_script_to_be_my_main_programming_language",
  "opinion_questions_the_java_script_ecosystem_is_changing_too_fast",
  "opinion_questions_this_survey_is_too_damn_long",
  "about_you_years_of_experience",
  "about_you_company_size",
  "about_you_how_did_you_find_out_about_this_survey",
  "about_you_your_gender",
  "about_you_your_country",
  "about_you_your_city",
  "about_you_yearly_salary",
  "about_you_other_comments"
];

export const foo = {
  about_you_years_of_experience: [
    "Less than one year",
    "1-2 years",
    "2-5 years",
    "5-10 years",
    "10-20 years",
    "20+ years"
  ],
  about_you_company_size: [
    "1-5 people",
    "Just me",
    "20-50 people",
    "50-100 people",
    "10-20 people",
    "5-10 people",
    "1000+ people",
    "100-1000 people"
  ],
  about_you_your_gender: [
    "Prefer not to say",
    "Male",
    "Non-binary/ third gender",
    "Female"
  ],
  about_you_yearly_salary: [
    "I work for free :(",
    "$0-$10k",
    "$10k-$30k",
    "$30k-$50k",
    "$50k-$100k",
    "$100k-$200k",
    "$200k+"
  ]
};
